#noconsole
[submodule "public_html/noconsole"]
	path = public_html/noconsole
	url = git@github.com:provtv/noconsole_fila5.git

#bashscripts
[submodule "bashscripts"]
	path = bashscripts
	url = git@github.com:provtv/bashscripts_fila5.git

#packages
[submodule "laravel/Modules/Lang/packages/lara-zeus/spatie-translatable"]
	path = laravel/Modules/Lang/packages/lara-zeus/spatie-translatable
	url = git@github.com:provtv/spatie-translatable.git


#modules xot
[submodule "laravel/Modules/Activity"]
	path = laravel/Modules/Activity
	url = git@github.com:provtv/module_activity_fila5.git
[submodule "laravel/Modules/DbForge"]
	path = laravel/Modules/DbForge
	url = git@github.com:provtv/module_dbforge_fila5.git
[submodule "laravel/Modules/Gdpr"]
	path = laravel/Modules/Gdpr
	url = git@github.com:provtv/module_gdpr_fila5.git
[submodule "laravel/Modules/Job"]
	path = laravel/Modules/Job
	url = git@github.com:provtv/module_job_fila5.git
[submodule "laravel/Modules/Lang"]
	path = laravel/Modules/Lang
	url = git@github.com:provtv/module_lang_fila5.git
[submodule "laravel/Modules/Media"]
	path = laravel/Modules/Media
	url = git@github.com:provtv/module_media_fila5.git
[submodule "laravel/Modules/Notify"]
	path = laravel/Modules/Notify
	url = git@github.com:provtv/module_notify_fila5.git
[submodule "laravel/Modules/Rating"]
	path = laravel/Modules/Rating
	url = git@github.com:provtv/module_rating_fila5.git
[submodule "laravel/Modules/Setting"]
	path = laravel/Modules/Setting
	url = git@github.com:provtv/module_setting_fila5.git
[submodule "laravel/Modules/Tenant"]
	path = laravel/Modules/Tenant
	url = git@github.com:provtv/module_tenant_fila5.git
[submodule "laravel/Modules/UI"]
	path = laravel/Modules/UI
	url = git@github.com:provtv/module_ui_fila5.git
[submodule "laravel/Modules/User"]
	path = laravel/Modules/User
	url = git@github.com:provtv/module_user_fila5.git
[submodule "laravel/Modules/Xot"]
	path = laravel/Modules/Xot
	url = git@github.com:provtv/module_xot_fila5.git

#modules ptv
[submodule "laravel/Modules/Badge"]
	path = laravel/Modules/Badge
	url = git@github.com:provtv/module_badge_fila5.git
[submodule "laravel/Modules/CertFisc"]
	path = laravel/Modules/CertFisc
	url = git@github.com:provtv/module_certfisc_fila5.git
[submodule "laravel/Modules/ContoAnnuale"]
	path = laravel/Modules/ContoAnnuale
	url = git@github.com:provtv/module_contoannuale_fila5.git
[submodule "laravel/Modules/Europa"]
	path = laravel/Modules/Europa
	url = git@github.com:provtv/module_europa_fila5.git
[submodule "laravel/Modules/Inail"]
	path = laravel/Modules/Inail
	url = git@github.com:provtv/module_inail_fila5.git
[submodule "laravel/Modules/Incentivi"]
	path = laravel/Modules/Incentivi
	url = git@github.com:provtv/module_incentivi_fila5.git
[submodule "laravel/Modules/IndennitaCondizioniLavoro"]
	path = laravel/Modules/IndennitaCondizioniLavoro
	url = git@github.com:provtv/module_indennitacondizionilavoro_fila5.git
[submodule "laravel/Modules/IndennitaResponsabilita"]
	path = laravel/Modules/IndennitaResponsabilita
	url = git@github.com:provtv/module_indennitaresponsabilita_fila5.git
[submodule "laravel/Modules/Legge104"]
	path = laravel/Modules/Legge104
	url = git@github.com:provtv/module_legge104_fila5.git
[submodule "laravel/Modules/Legge109"]
	path = laravel/Modules/Legge109
	url = git@github.com:provtv/module_legge109_fila5.git
[submodule "laravel/Modules/Mensa"]
	path = laravel/Modules/Mensa
	url = git@github.com:provtv/module_mensa_fila5.git
[submodule "laravel/Modules/MobilitaVolontaria"]
	path = laravel/Modules/MobilitaVolontaria
	url = git@github.com:provtv/module_mobilitavolontaria_fila5.git
[submodule "laravel/Modules/Pdnd"]
	path = laravel/Modules/Pdnd
	url = git@github.com:provtv/module_pdnd_fila5.git
[submodule "laravel/Modules/Performance"]
	path = laravel/Modules/Performance
	url = git@github.com:provtv/module_performance_fila5.git
[submodule "laravel/Modules/Prenotazioni"]
	path = laravel/Modules/Prenotazioni
	url = git@github.com:provtv/module_prenotazioni_fila5.git
[submodule "laravel/Modules/PresenzeAssenze"]
	path = laravel/Modules/PresenzeAssenze
	url = git@github.com:provtv/module_presenzeassenze_fila5.git
[submodule "laravel/Modules/Progressioni"]
	path = laravel/Modules/Progressioni
	url = git@github.com:provtv/module_progressioni_fila5.git
[submodule "laravel/Modules/Ptv"]
	path = laravel/Modules/Ptv
	url = git@github.com:provtv/module_ptv_fila5.git
[submodule "laravel/Modules/Questionari"]
	path = laravel/Modules/Questionari
	url = git@github.com:provtv/module_questionari_fila5.git
[submodule "laravel/Modules/Sigma"]
	path = laravel/Modules/Sigma
	url = git@github.com:provtv/module_sigma_fila5.git
[submodule "laravel/Modules/Sindacati"]
	path = laravel/Modules/Sindacati
	url = git@github.com:provtv/module_sindacati_fila5.git



#themes	
[submodule "laravel/Themes/Zero"]
	path = laravel/Themes/Zero
	url = git@github.com:provtv/theme_zero_fila5.git


#to order !




