<?php

declare(strict_types=1);

namespace Modules\Performance\Filament\Resources\IndividualeAdmResource\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Component;
use Modules\Xot\Filament\Resources\Schemas\XotBaseResourceInfolist;

class IndividualeAdmInfolist extends XotBaseResourceInfolist
{
    /**
     * @return array<string, Component>
     */
    public static function getInfolistSchema(): array
    {
        return [
            'type' => TextEntry::make('type'),
            'post_type' => TextEntry::make('post_type'),
            'ente' => TextEntry::make('ente'),
            'matr' => TextEntry::make('matr'),
            'cognome' => TextEntry::make('cognome'),
            'nome' => TextEntry::make('nome'),
            'email' => TextEntry::make('email'),
            'stabi' => TextEntry::make('stabi'),
            'repar' => TextEntry::make('repar'),
            'stabival' => TextEntry::make('stabival'),
            'reparval' => TextEntry::make('reparval'),
            'stabi_txt' => TextEntry::make('stabi_txt'),
            'repar_txt' => TextEntry::make('repar_txt'),
            'disci' => TextEntry::make('disci'),
            'disci_txt' => TextEntry::make('disci_txt'),
            'rep2kd' => TextEntry::make('rep2kd'),
            'rep2ka' => TextEntry::make('rep2ka'),
            'posiz' => TextEntry::make('posiz'),
            'propro' => TextEntry::make('propro'),
            'posfun' => TextEntry::make('posfun'),
            'categoria_eco' => TextEntry::make('categoria_eco'),
            'qua2kd' => TextEntry::make('qua2kd'),
            'qua2ka' => TextEntry::make('qua2ka'),
            'dal' => TextEntry::make('dal'),
            'al' => TextEntry::make('al'),
            'anno' => TextEntry::make('anno'),
            'giornitempodet' => TextEntry::make('giornitempodet'),
            'ha_diritto' => TextEntry::make('ha_diritto'),
            'motivo' => TextEntry::make('motivo'),
            'esperienza_acquisita' => TextEntry::make('esperienza_acquisita'),
            'risultati_ottenuti' => TextEntry::make('risultati_ottenuti'),
            'arricchimento_professionale' => TextEntry::make('arricchimento_professionale'),
            'impegno' => TextEntry::make('impegno'),
            'qualita_prestazione' => TextEntry::make('qualita_prestazione'),
            'totale_punteggio' => TextEntry::make('totale_punteggio'),
            'lista_auth' => TextEntry::make('lista_auth'),
            'peso_esperienza_acquisita' => TextEntry::make('peso_esperienza_acquisita'),
            'peso_risultati_ottenuti' => TextEntry::make('peso_risultati_ottenuti'),
            'peso_arricchimento_professionale' => TextEntry::make('peso_arricchimento_professionale'),
            'peso_impegno' => TextEntry::make('peso_impegno'),
            'peso_qualita_prestazione' => TextEntry::make('peso_qualita_prestazione'),
            'datemod' => TextEntry::make('datemod'),
            'note' => TextEntry::make('note'),
            'oree' => TextEntry::make('oree'),
            'oret' => TextEntry::make('oret'),
            'perc_parttime' => TextEntry::make('perc_parttime'),
            'perc_parttimepond' => TextEntry::make('perc_parttimepond'),
            'gg_parttimevert' => TextEntry::make('gg_parttimevert'),
            'ore_assenza' => TextEntry::make('ore_assenza'),
            'giorni_assenza' => TextEntry::make('giorni_assenza'),
            'giorni_presenza' => TextEntry::make('giorni_presenza'),
            'categ_coeff' => TextEntry::make('categ_coeff'),
            'quota_teorica' => TextEntry::make('quota_teorica'),
            'budget_assegnato' => TextEntry::make('budget_assegnato'),
            'quota_effettiva' => TextEntry::make('quota_effettiva'),
            'resti' => TextEntry::make('resti'),
            'resti_pond' => TextEntry::make('resti_pond'),
            'importo_totale' => TextEntry::make('importo_totale'),
            'gg_totale_sigma' => TextEntry::make('gg_totale_sigma'),
            'gg_validi_sigma' => TextEntry::make('gg_validi_sigma'),
            'gg_assenz_sigma' => TextEntry::make('gg_assenz_sigma'),
            'decurtazione_perc' => TextEntry::make('decurtazione_perc'),
            'gg_tempo_determinato' => TextEntry::make('gg_tempo_determinato'),
            'gg_posiz_1_in_sede' => TextEntry::make('gg_posiz_1_in_sede'),
            'gg_assenza_anno' => TextEntry::make('gg_assenza_anno'),
            'gg_presenza_anno' => TextEntry::make('gg_presenza_anno'),
            'ore_assenza_anno' => TextEntry::make('ore_assenza_anno'),
            'posiz_txt' => TextEntry::make('posiz_txt'),
            'clafun' => TextEntry::make('clafun'),
            'disci1' => TextEntry::make('disci1'),
            'disci1_txt' => TextEntry::make('disci1_txt'),
            'gg_ruolo' => TextEntry::make('gg_ruolo'),
            'last_data_assunz' => TextEntry::make('last_data_assunz'),
            'perc_parttime_anno' => TextEntry::make('perc_parttime_anno'),
            'perc_parttime_dalal' => TextEntry::make('perc_parttime_dalal'),
            'gg_parttimevert_anno' => TextEntry::make('gg_parttimevert_anno'),
            'gg_parttimevert_dalal' => TextEntry::make('gg_parttimevert_dalal'),
            'perc_parttimepond_anno' => TextEntry::make('perc_parttimepond_anno'),
            'perc_parttimepond_dalal' => TextEntry::make('perc_parttimepond_dalal'),
            'gg_presenza_dalal' => TextEntry::make('gg_presenza_dalal'),
            'gg_assenza_dalal' => TextEntry::make('gg_assenza_dalal'),
            'hh_assenza_anno' => TextEntry::make('hh_assenza_anno'),
            'hh_assenza_dalal' => TextEntry::make('hh_assenza_dalal'),
            'lang' => TextEntry::make('lang'),
            'excellence' => TextEntry::make('excellence'),
            'codqua' => TextEntry::make('codqua'),
            'cont' => TextEntry::make('cont'),
            'tipco' => TextEntry::make('tipco'),
            'posizione_eco' => TextEntry::make('posizione_eco'),
            'gg_anno' => TextEntry::make('gg_anno'),
            'created_by' => TextEntry::make('created_by'),
            'id' => TextEntry::make('id'),
            'soldi' => TextEntry::make('soldi'),
            'info' => TextEntry::make('info'),
            'pdf' => TextEntry::make('pdf'),
            'send_mail' => TextEntry::make('send_mail'),
            'zip_schede' => TextEntry::make('zip_schede'),
        ];
    }
}
