# Deprecato — SSOT: laravel/config/vhost/ptvx.local.conf
DocumentRoot /var/www/_bases/base_ptvx_fila5/public_html

ServerName ptvx.local

<Directory "/var/www/html/base_ptvx_fila5/public_html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
